import { Document, Page, Text, View, Image, StyleSheet } from "@react-pdf/renderer";
import { COLORS, PAGE } from "./styles/pdfStyles";
import { formatMonthYear } from "@/utils/formatDate";

export interface SeasonalityPdfChart {
  label: string;
  imageDataUrl: string;
}

export interface SeasonalityPdfDocumentProps {
  regionName: string;
  illnessLabel: string;
  forecastPeriod: { start: string; end: string };
  charts: SeasonalityPdfChart[];
  exportTimestamp: string;
}

const styles = StyleSheet.create({
  page: {
    backgroundColor: COLORS.navy,
    color: COLORS.offwhite,
    fontFamily: "Helvetica",
    fontSize: 9,
    padding: PAGE.padding,
    paddingBottom: 56,
  },
  cover: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  coverTitle: {
    color: COLORS.offwhite,
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 6,
  },
  coverSubtitle: {
    color: COLORS.tealBright,
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 32,
  },
  coverMeta: {
    width: "100%",
    maxWidth: 360,
  },
  coverField: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.border,
  },
  coverLabel: {
    color: COLORS.muted,
    fontSize: 9,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  coverValue: {
    color: COLORS.offwhite,
    fontSize: 9,
    fontWeight: "bold",
    textAlign: "right",
    maxWidth: "60%",
  },
  sectionHeading: {
    color: COLORS.tealBright,
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 8,
  },
  chartImage: {
    width: "100%",
    maxHeight: 380,
  },
  footerPage: {
    position: "absolute",
    bottom: 20,
    left: PAGE.padding,
    right: PAGE.padding,
    borderTopWidth: 0.5,
    borderTopColor: COLORS.border,
    paddingTop: 8,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 7,
    color: COLORS.muted,
  },
});

function CoverField({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.coverField}>
      <Text style={styles.coverLabel}>{label}</Text>
      <Text style={styles.coverValue}>{value}</Text>
    </View>
  );
}

export function SeasonalityPdfDocument({
  regionName,
  illnessLabel,
  forecastPeriod,
  charts,
  exportTimestamp,
}: SeasonalityPdfDocumentProps) {
  return (
    <Document>
      {/* Cover Page */}
      <Page size="A4" style={styles.page}>
        <View style={styles.cover}>
          <Text style={styles.coverTitle}>HEALTHWATCH</Text>
          <Text style={styles.coverSubtitle}>Seasonal Pattern Analysis Report</Text>

          <View style={styles.coverMeta}>
            <CoverField label="Region" value={regionName} />
            <CoverField label="Illness" value={illnessLabel} />
            <CoverField
              label="Forecast Period"
              value={`${formatMonthYear(forecastPeriod.start)} to ${formatMonthYear(forecastPeriod.end)}`}
            />
            <CoverField label="Generated" value={formatMonthYear(exportTimestamp)} />
            <CoverField label="Source" value="DOH PIDSR Surveillance Data" />
          </View>
        </View>

        <View style={styles.footerPage}>
          <Text>HealthWatch</Text>
          <Text>Page 1</Text>
        </View>
      </Page>

      {/* Chart Pages */}
      {charts.map((chart, i) => (
        <Page key={i} size="A4" style={styles.page}>
          <View style={{ marginTop: 8 }}>
            <Text style={styles.sectionHeading}>{chart.label}</Text>
            <Image src={chart.imageDataUrl} style={styles.chartImage} />
          </View>

          <View style={styles.footerPage}>
            <Text>HealthWatch · Seasonal Pattern Analysis</Text>
            <Text>Page {i + 2}</Text>
          </View>
        </Page>
      ))}

      {/* Footer Page */}
      <Page size="A4" style={styles.page}>
        <View style={{ flex: 1, justifyContent: "flex-end", alignItems: "center" }}>
          <Text
            style={{
              color: COLORS.offwhite,
              fontSize: 11,
              fontWeight: "bold",
              marginBottom: 8,
            }}
          >
            Generated by HealthWatch
          </Text>
          <Text style={{ color: COLORS.muted, fontSize: 9, marginBottom: 4 }}>
            Regional Time-Series Analysis System
          </Text>
          <Text style={{ color: COLORS.muted, fontSize: 8 }}>
            Source: DOH PIDSR Surveillance Data | For public health decision support only
          </Text>
        </View>

        <View style={styles.footerPage}>
          <Text>HealthWatch</Text>
          <Text>Page {charts.length + 2}</Text>
        </View>
      </Page>
    </Document>
  );
}
