import { Text, View } from "@react-pdf/renderer";
import { pdfStyles } from "../styles/pdfStyles";

/**
 * Fixed footer repeated on every page with the DOH sourcing notice.
 */
export function PDFFooter() {
  return (
    <View fixed style={pdfStyles.footer}>
      <Text style={pdfStyles.footerLine}>
        Data sourced from the Department of Health (DOH), Philippines.
      </Text>
      <Text style={pdfStyles.footerLine}>
        This report is generated by HEALTHWATCH and is for surveillance purposes only.
      </Text>
    </View>
  );
}
