/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as SeasonalityRouteImport } from './routes/seasonality'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegionCodeRouteImport } from './routes/region.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonalityRoute = SeasonalityRouteImport.update({
  id: '/seasonality',
  path: '/seasonality',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionCodeRoute = RegionCodeRouteImport.update({
  id: '/region/$code',
  path: '/region/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/methodology': typeof MethodologyRoute
  '/seasonality': typeof SeasonalityRoute
  '/settings': typeof SettingsRoute
  '/region/$code': typeof RegionCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/methodology': typeof MethodologyRoute
  '/seasonality': typeof SeasonalityRoute
  '/settings': typeof SettingsRoute
  '/region/$code': typeof RegionCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/methodology': typeof MethodologyRoute
  '/seasonality': typeof SeasonalityRoute
  '/settings': typeof SettingsRoute
  '/region/$code': typeof RegionCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/methodology'
    | '/seasonality'
    | '/settings'
    | '/region/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/methodology'
    | '/seasonality'
    | '/settings'
    | '/region/$code'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/methodology'
    | '/seasonality'
    | '/settings'
    | '/region/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  MethodologyRoute: typeof MethodologyRoute
  SeasonalityRoute: typeof SeasonalityRoute
  SettingsRoute: typeof SettingsRoute
  RegionCodeRoute: typeof RegionCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasonality': {
      id: '/seasonality'
      path: '/seasonality'
      fullPath: '/seasonality'
      preLoaderRoute: typeof SeasonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region/$code': {
      id: '/region/$code'
      path: '/region/$code'
      fullPath: '/region/$code'
      preLoaderRoute: typeof RegionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  MethodologyRoute: MethodologyRoute,
  SeasonalityRoute: SeasonalityRoute,
  SettingsRoute: SettingsRoute,
  RegionCodeRoute: RegionCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
